config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    member do
      put 'like', to: "posts#like"
      put 'unlike', to: "posts#unlike"
    end
  end
  root 'posts#index'

  devise_for :users, controllers: { sessions: "sessions", registrations: 'registrations' }

  post '/follow/:id' => 'followings#create', as: 'follow'
  delete '/follow/:id' => 'followings#destroy', as: 'unfollow'

  get '/accounts' => 'home#accounts', as: 'accounts'

  get '/:id' => 'home#profile', as: 'profile'
  get '/accounts/edit' => 'home#edit', as: 'edit_profile'
  post '/accounts/edit' => 'home#update', as: 'update_profile'
  get '/accounts/password' => 'home#edit_password', as: 'edit_password'
  post '/accounts/password' => 'home#update_password', as: 'update_password'

  delete '/user/delete' => 'home#destroy', as: 'delete_user'

end

app/models/allowed.rb
class Allowed < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_one_attached :image
end

app/models/upload.rb
class Upload < ApplicationRecord
end

app/models/uploadable.rb
class Uploadable < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :posts
  has_many :followings
  acts_as_voter
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def create
    @following = current_user.followings.build
    @following.following = params[:id]
    if @following.save
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    @following = Following.find_by(following: params[:id], user_id: current_user.id)
    @following.destroy
    redirect_back fallback_location: root_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "krish"
  before_action :authenticate_user!

  def profile
    @user = User.find_by(username: params[:id])
    @posts = @user.posts.order("created_at DESC")
    @followings = Following.where(user_id: current_user.id).pluck('following')
  end

  def accounts
    @accounts = User.all
    @followings = Following.where(user_id: current_user.id).pluck('following')
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to profile_path(@user.username) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to profile_path(@user.username) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    current_user.delete
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :username, :email, :password, :password_confirmation, :current_password, :contact, :bio, :avatar_shot, :website, :gender)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  layout "krish"
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    followings = Following.where(user_id: current_user.id).pluck('following')
    users = followings << current_user.id
    @posts = Post.where(user_id: users).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find(@post.user_id)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @post = Post.find(params[:id])
    @post.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js { render layout: false }
    end
  end

  def unlike
    @post = Post.find(params[:id])
    @post.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :caption, :image, :image_shot)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:avatar, :name, :username, :email, :password, :password_confirmation, :contact, :bio, :avatar_shot, :website, :gender)
  end

  def account_update_params
    params.require(:user).permit(:avatar, :name, :username, :email, :password, :password_confirmation, :current_password, :contact, :bio, :avatar_shot, :website, :gender)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    @user = User.find_by(contact: user_params[:username]) ||
            User.find_by(username: user_params[:username]) ||
            User.find_by(email: user_params[:username])
    if @user && @user.valid_password?(user_params[:password])
      sign_in(@user)
    end
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/accounts.html.erb
<div class="columns">
  <div class="column is-8">
    <div class="columns">
      <div class="column">
        <p class="control title is-4">Who to follow?</p>
      </div>
    </div>
    <div class="columns is-multiline is-mobile">
      <% @accounts.each do |a| %>
        <% unless a == current_user %>
          <% unless a.id.in?(@followings) %>
            <div class="column is-6">
              <%= link_to profile_path(a.username) do %>
                  <div class="card">
                    <div class="card-content">
                      <div class="media">
                        <div class="media-left">
                          <figure class="image is-48x48">
                            <% if Allowed.count == 0 && !a.avatar_shot.nil? && a.avatar_shot!="" %>
                              <img src="<%= a.avatar_shot %>">
                            <% elsif Allowed.count!=0 && a.avatar.attached? %>
                              <%= image_tag a.avatar %>
                            <% else %>
                              <img src="https://bulma.io/images/placeholders/128x128.png">
                            <% end %>
                          </figure>
                        </div>
                        <div class="media-content">
                          <p class="control"><strong><%= a.name %></strong></p>
                          <p class="control"><small><%= a.username %></small></p>
                        </div>
                      </div>
                    </div>
                  </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="column is-4">
    <div class="panel">
      <p class="panel-heading">Following List</p>
      <% current_user.followings.each do |u| %>
        <% user = User.find(u.following) %>
        <%= link_to profile_path(user.username) do %>
        <div class="panel-block">
          <article class="media">
            <div class="media-left">
              <figure class="media-left">
                <p class="image is-48x48">
                  <% if Allowed.count == 0 && !user.avatar_shot.nil? && user.avatar_shot!="" %>
                    <img src="<%= user.avatar_shot %>">
                  <% elsif Allowed.count!=0 && user.avatar.attached? %>
                    <%= image_tag user.avatar %>
                  <% else %>
                    <img src="https://bulma.io/images/placeholders/128x128.png">
                  <% end %>
                </p>
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <p>
                  <strong><%= user.name %></strong><br/>
                  <small>@<%= user.username %></small>
                </p>
              </div>
            </div>
          </article>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/edit.html.erb
<%= form_for @user, url: update_profile_path, method: :post do |f| %>

  <div class="columns is-gapless full-height">
    <div class="column is-3">
      <div class="card">
        <div class="card-content">
          <%= link_to edit_profile_path do %>
            <p class="control has-text-weight-medium is-size-5">Edit Profile</p>
          <% end %><br>
          <%= link_to edit_password_path do %>
            <p class="control is-size-6">Change Password</p>
          <% end %><br>
        </div>
      </div>
    </div>
    <div class="column is-9">
      <div class="card">
        <div class="card-content">

          <% if Allowed.count == 0 %>
            <% if !current_user.avatar_shot.nil? && current_user.avatar_shot!="" %>
              <div class="columns">
                <div class="column control has-text-right">
                  <figure class="image is-128x128 has-image-centered">
                    <img src="<%= current_user.avatar_shot %>" alt="">
                  </figure>
                </div>
              </div>
            <% else %>
                <br>
            <% end %>
          <% else %>
            <% if @user.avatar.attached? %>
              <div class="columns">
                <div class="column control has-text-right">
                  <figure class="image is-128x128 has-image-centered">
                    <%= image_tag @user.avatar %>
                  </figure>
                </div>
              </div>
            <% else %>
              <br>
            <% end %>
          <% end %>

          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Name</strong>
            </div>
            <div class="column is-8">
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
            </div>
            <div class="column is-8">
              <small>Help people discover your account by using the name you're known by: either your full name, nickname, or business name.</small>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Username</strong>
            </div>
            <div class="column is-8">
              <%= f.text_field :username, autofocus: true, autocomplete: "username", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Website</strong>
            </div>
            <div class="column is-8">
              <%= f.text_field :website, autofocus: true, autocomplete: "username", class: 'input' %>
            </div>
          </div>

          <% if Allowed.count == 0 %>
            <div class="columns">
              <div class="column is-4 control has-text-right">
                <strong>Dp</strong>
              </div>
              <div class="column is-8">
                <%= f.text_field :avatar_shot, autofocus: true, autocomplete: "username", class: 'input' %>
              </div>
            </div>
          <% else %>
            <div class="columns">
              <div class="column is-4 control has-text-right">
                <strong>Dp</strong>
              </div>
              <div class="column is-8">
                <%= f.file_field :avatar, autofocus: true, autocomplete: "username", class: 'input' %>
              </div>
            </div>
          <% end %>

          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Bio</strong>
            </div>
            <div class="column is-8">
              <%= f.text_area :bio, autofocus: true, autocomplete: "bio", class: 'textarea', rows: 3 %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
            </div>
            <div class="column is-8">
              <p>Personal Information<br>
              <small>Provide your personal information, even if the account is used for a business, a pet or something else. This won't be a part of your public profile.</small></p>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Email</strong>
            </div>
            <div class="column is-8">
              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Phone number</strong>
            </div>
            <div class="column is-8">
              <%= f.text_field :contact, autofocus: true, autocomplete: "contact", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Gender</strong>
            </div>
            <div class="column is-8">
              <div class="select">
                <%= f.select :gender, [['Select gender', nil], 'Male', 'Female', 'Others'],autofocus: true, autocomplete: "username" %>
              </div>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right"></div>
            <div class="column is-8">
              <div class="columns">
                <div class="column">
                  <%= f.submit 'Update', class: 'button is-info' %>
                </div>
                <div class="column control has-text-right">
                  <%= link_to delete_user_path, method: :delete, data: { confirm: "Are you sure want to cancel your account?" }, class: "button is-danger" do %>
                    Cancel my account
                  <% end %><br><br>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/home/edit_password.html.erb
<%= form_for @user, url: user_registration_path, method: :patch do |f| %>

  <div class="columns is-gapless full-height">
    <div class="column is-3">
      <div class="card">
        <div class="card-content">
          <%= link_to edit_profile_path do %>
            <p class="control is-size-6">Edit Profile</p>
          <% end %><br>
          <%= link_to edit_password_path do %>
            <p class="control has-text-weight-medium is-size-5">Change Password</p>
          <% end %><br>
        </div>
      </div>
    </div>
    <div class="column is-9">
      <div class="card">
        <div class="card-content">

          <% if Allowed.count == 0 %>
            <% if !current_user.avatar_shot.nil? && current_user.avatar_shot!="" %>
              <div class="columns">
                <div class="column control has-text-right">
                  <figure class="image is-128x128 has-image-centered">
                    <img src="<%= current_user.avatar_shot %>" alt="">
                  </figure>
                </div>
              </div>
            <% else %>
                <br>
            <% end %>
          <% else %>
            <% if @user.avatar.attached? %>
              <div class="columns">
                <div class="column control has-text-right">
                  <figure class="image is-128x128 has-image-centered">
                    <%= image_tag @user.avatar %>
                  </figure>
                </div>
              </div>
            <% else %>
              <br>
            <% end %>
          <% end %>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Old Password</strong>
            </div>
            <div class="column is-8">
              <%= f.password_field :current_password, autofocus: true, autocomplete: "name", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>New Password</strong>
            </div>
            <div class="column is-8">
              <%= f.password_field :password, autofocus: true, autocomplete: "username", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right">
              <strong>Confirm Password</strong>
            </div>
            <div class="column is-8">
              <%= f.password_field :password_confirmation, autofocus: true, autocomplete: "username", class: 'input' %>
            </div>
          </div>
          <div class="columns">
            <div class="column is-4 control has-text-right"></div>
            <div class="column is-8">
              <div class="columns">
                <div class="column">
                  <%= f.submit 'Change Password', class: 'button is-info' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

<style media="screen">

  a {
    color: black;
  }
  .has-image-centered {
    margin-left: auto;
    margin-right: auto;
  }
  .card {
    height: 100%;
  }
</style>

app/views/home/profile.html.erb
<div class="column is-three-fifths is-offset-one-fifth">

  <div class="columns">

    <div class="column is-4">
      <figure class="image is-128x128">
        <% if Allowed.count == 0 && !@user.avatar_shot.nil? && @user.avatar_shot!="" %>
          <img src="<%= @user.avatar_shot %>">
        <% elsif Allowed.count!=0 && @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <% else %>
          <img src="https://bulma.io/images/placeholders/128x128.png">
        <% end %>
      </figure>
    </div>

    <div class="column is-8">
      <div class="content is-normal">
        <strong class="title is-3"><%= @user.username %></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <% if @user == current_user %>
          <%= link_to edit_profile_path, class: "button" do %>
            Edit Profile
          <% end %>
        <% else %>
          <% if @user.id.in?(@followings) %>
            <%= link_to unfollow_path(@user), method: :delete, class: 'button is-info' do %>
              Unfollow
            <% end %>
          <% else %>
            <%= link_to follow_path(@user), method: :post, class: 'button is-info' do %>
              Follow
            <% end %>
          <% end %>
        <% end %>
        <br><br>
        <div class="columns">
          <div class="column control is-size-5"><strong><%= @user.posts.count %></strong> <small>posts</small></div>
          <div class="column control is-size-5"><strong><%= Following.where(following: @user.id).count %></strong> <small>followers</small></div>
          <div class="column control is-size-5"><strong><%= Following.where(user_id: @user.id).count %></strong> <small>followings</small></div>
        </div>
        <p class="control is-size-6"><%= @user.name %></p>
        <p class="control is-size-6"><%= @user.bio %></p>
      </div>
    </div>
  </div>
  <hr />
  <div class="columns is-multiline is-mobile">
    <% @posts.each do |post| %>
      <div class="column is-4">
        <div class="card">
          <div class="card-image">
            <figure class="container-img">
              <%= link_to post_path(post) do %>
                <% if !post.image_shot.nil? && post.image_shot!="" %>
                  <img src="<%= post.image_shot %>" alt="">
                <% else %>
                  <%= image_tag post.image %>
                <% end %>
              <% end %>
            </figure>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Overpass+Mono" rel="stylesheet">
    <style media="screen">
      /* We don't need checkbox to be displayed in order for it to work */
      .toggler {
        display: none;
      }

      /* Below are all the functionalities */

      /* Hamburger changes to X when toggler is checked */
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(1) {
        -webkit-transform: translateY(5px) rotate(45deg);
        transform: translateY(5px) rotate(45deg);
      }
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(2) {
        opacity: 0;
      }
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(3) {
        -webkit-transform: translateY(-5px) rotate(-45deg);
        transform: translateY(-5px) rotate(-45deg);
      }

      /*  Displays menu when toggler is checked only on mobile/tablet */
      @media screen and (max-width: 1024px) {
        .navbar .toggler:checked ~ .navbar-menu {
          display: block;
        }
        /* We don't want menu to be displayed on mobile by default */
        .navbar-menu {
          display: none;
        }
      }
    </style>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/layouts/krish.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'krish', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style media="screen">
      /* We don't need checkbox to be displayed in order for it to work */
      .toggler {
        display: none;
      }

      /* Below are all the functionalities */

      /* Hamburger changes to X when toggler is checked */
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(1) {
        -webkit-transform: translateY(5px) rotate(45deg);
        transform: translateY(5px) rotate(45deg);
      }
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(2) {
        opacity: 0;
      }
      .navbar .toggler:checked + .navbar-brand .burger span:nth-child(3) {
        -webkit-transform: translateY(-5px) rotate(-45deg);
        transform: translateY(-5px) rotate(-45deg);
      }

      /*  Displays menu when toggler is checked only on mobile/tablet */
      @media screen and (max-width: 1024px) {
        .navbar .toggler:checked ~ .navbar-menu {
          display: block;
        }
        /* We don't want menu to be displayed on mobile by default */
        .navbar-menu {
          display: none;
        }
      }
    </style>
  </head>

  <body>
        <nav class="navbar is-fixed-top is-white">
          <div class="container">

            <div class="navbar-brand">
              <a class="navbar-item" href="/">
                <img src="https://www.instagram.com/static/images/web/mobile_nav_type_logo.png/735145cfe0a4.png" alt="Instagram">
              </a>
              <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>

            <div id="navbarExampleTransparentExample" class="navbar-menu">
              <div class="navbar-end">
                <div class="field is-grouped">
                  <%= link_to root_path, class: 'navbar-item icon-padding' do %>
                    <figure class="control icon"><i class="fa fa-home fa-2x" aria-hidden="true"></i></figure>
                  <% end %>
                  <%= link_to new_post_path, class: 'navbar-item icon-padding' do %>
                    <figure class="control icon"><i class="fa fa-plus fa-2x" aria-hidden="true"></i></figure>
                  <% end %>
                  <%= link_to accounts_path, class: 'navbar-item icon-padding' do %>
                    <figure class="control icon"><i class="fa fa-user fa-2x" aria-hidden="true"></i></figure>
                  <% end %>
                  <%= link_to profile_path(current_user.username), class: 'navbar-item icon-padding' do %>
                    <figure class="control image-navbar is-48x48">
                      <% if Allowed.count == 0 && !current_user.avatar_shot.nil? && current_user.avatar_shot!="" %>
                        <img src="<%= current_user.avatar_shot %>">
                      <% elsif Allowed.count!=0 && current_user.avatar.attached? %>
                        <%= image_tag current_user.avatar %>
                      <% else %>
                        <img src="https://bulma.io/images/placeholders/128x128.png">
                      <% end %>
                    </figure>
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to log out?" }, class: 'navbar-item icon-padding' do %>
                    <figure class="control icon"><i class="fa fa-sign-out fa-2x" aria-hidden="true"></i></figure>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </nav>
        <section class="section body">
          <div class="container">
            <br>
            <%= yield %>
          </div>
        </section>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="columns">
  <div class="column is-6 is-offset-3">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <% if Allowed.count == 0 && !user.avatar_shot.nil? && user.avatar_shot!="" %>
                <img src="<%= user.avatar_shot %>">
              <% elsif Allowed.count!=0 && user.avatar.attached? %>
                <%= image_tag user.avatar %>
              <% else %>
                <img src="https://bulma.io/images/placeholders/48x48.png">
              <% end %>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-6">
              <%= link_to profile_path(user.username) do %>
                <%= user.name %>
              <% end %>
            </p>
            <p class="subtitle is-6">@<%= user.username %></p>
          </div>
        </div>
      </div>
      <div class="card-image">
        <figure class="container-img">
          <% if !post.image_shot.nil? && post.image_shot!="" %>
            <img src="<%= post.image_shot %>" alt="">
          <% else %>
            <%= image_tag post.image %>
          <% end %>
        </figure>
      </div>
      <div class="card-content">
        <div class="level-left likes data">
          <% if user_signed_in? %>
            <% if current_user.liked? post %>
              <%= link_to unlike_post_path(post), method: :put, class: "unlike_post" do %>
                <span class="icon"><i class="fa fa-heart has-text-primary"></i></span>
                <span class="vote_count"><%= pluralize(post.get_likes.size, 'Like') %></span>
              <% end %>
            <% else %>
              <%= link_to like_post_path(post), method: :put, class: "like_post" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(post.get_likes.size, 'Like') %></span>
              <% end %>
            <% end %>
          <% else %>
              <%= link_to like_post_path(post), method: :put, class: "like_post" do %>
                <span class="icon"><i class="fa fa-heart"></i></span>
                <span class="vote_count"><%= pluralize(post.get_likes.size, 'Like') %></span>
              <% end %>
          <% end %>
        </div>
        <strong>
          <%= link_to profile_path(user.username) do %>
            <%= user.username %>
          <% end %>
        </strong>&nbsp;
        <%= post.caption %><br>
        <hr>
        <p><small><%= time_ago_in_words(post.created_at).upcase %> AGO</small></p>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <% user = User.find(post.user_id)%>
  <%= render 'post', post: post, user: user %>
<% end %>

app/views/posts/new.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <div class="box">
      <%= render 'form', post: @post %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'post', user: @user, post: @post%>